### ISSUE TITLE
hangup when typing in Cloud2 UI

### ISSUE THREAD

**Issue by rogpeppe** [influxdata/flux-lsp#198] opened 2020-12-18 08:07 UTC
See this issue for details: https://github.com/influxdata/ui/issues/443

**Comment by scbrickley** [comment] 2020-12-18 15:01
Copied and pasted from the original issue, just for convenience: 

> Steps to reproduce:
> 
> In a script editor in Data Explorer, paste this text:
> `union(tables: [a`
> then start typing this text after the final `[a`:
> `, ini`
> This hangs up forever for me
> 
> Environment info:
> 
> Cloud2.
> Chrome 87.0.4280.66

**Comment by scbrickley** [comment] 2020-12-18 16:20
Confirmed that this happens in OSS as well.

No networks requests are made, and the bug persists even when re-enabling callbacks disabled in #194. QED, this bug is distinct from #190, but presents similarly.

**Comment by scbrickley** [comment] 2021-03-03 20:01
Pretty sure this was caused by https://github.com/influxdata/idpe/issues/9592, which was resolved in https://github.com/influxdata/flux/pull/3487. Closing this issue for now. If the problem persists, feel free to open it again.

**Closed** 2021-04-12 20:38 UTC
Labels: kind/bug, team/query
